# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f73f02736ac6fdf070758b532e77cea9012e3b59a23e77cfef5c760fd931a35e2602782cdc2fc4aee37745e1e4dbdfe3553e745bbf7d6801c71fa7156be3d4d

test:
  secret_key_base: 23546c924f90b682cb43f60d4ae52b597844def1d94eaa15f2a4504df8f3a4167f11b19a4d7cf866f520839f3802d277e08765908beaf2b88d9b68abda6b20d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
